[project]
name = "sudokusolver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "python-sat[aiger,approxmc,cryptosat,pblib]>=1.8.dev13",
    "ruff>=0.7.2",
]
